# Generated by Django 5.2.4 on 2025-07-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('curso', models.CharField(choices=[('CC', 'Ciência da Computação'), ('ENG-QUI', 'Engenharia Química'), ('ENG-MEC', 'Engenharia Mecânica'), ('GEST-AGRO', 'Gestão do Agro'), ('TECS', 'Cursos Técnicos')], default='CC', max_length=20)),
                ('quant_de_pecas', models.IntegerField()),
                ('cor', models.CharField(max_length=20)),
                ('telefone', models.IntegerField()),
                ('arq_upload', models.FileField(blank=True, null=True, upload_to='arquivos/')),
                ('arq_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
