# Generated by Django 5.2.4 on 2025-08-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('curso', models.CharField(choices=[('CC', 'Ciência da Computação'), ('ENG-QUI', 'Engenharia Química'), ('ENG-MEC', 'Engenharia Mecânica'), ('GEST-AGRO', 'Gestão do Agronegocio'), ('TECS', 'Cursos Técnicos')], default='CC', max_length=20)),
                ('quant_de_pecas', models.IntegerField()),
                ('cor', models.CharField(max_length=20)),
                ('telefone', models.IntegerField(unique=True)),
                ('arq_upload', models.FileField(blank=True, null=True, upload_to='arquivos/')),
                ('arq_link', models.URLField(blank=True, null=True)),
                ('tipo_preenchimento', models.CharField(blank=True, max_length=50, null=True)),
                ('resolucao', models.CharField(blank=True, choices=[('BAIXO', 'baixo'), ('MEDIO', 'medio'), ('ALTO', 'alto')], default='BAIXO', max_length=20, null=True)),
                ('qual_impressora', models.CharField(blank=True, choices=[('Ender_V2', 'Ender V2'), ('Ender_3-SE', 'Ender 3 SE'), ('Ender_3-S1', 'Ender 3 S1'), ('Ender_5-plus', 'Ender 5 Plus')], default='Ender_V2', max_length=20, null=True)),
                ('porcentagem_preenchimento', models.IntegerField()),
                ('Tipo_filamento', models.CharField(blank=True, choices=[('PLA', 'pla'), ('ABS', 'abs'), ('PETG', 'petg')], default='PLA', max_length=20, null=True)),
            ],
        ),
    ]
