# Generated by Django 5.2.4 on 2025-10-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='Tipo_filamento',
        ),
        migrations.AlterField(
            model_name='models',
            name='curso',
            field=models.CharField(choices=[('CC', 'Ciência da Computação'), ('ENG-QUI', 'Engenharia Química'), ('ENG-MEC', 'Engenharia Mecânica'), ('GEST-AGRO', 'Gestão do Agronegócio'), ('TECS', 'Cursos Técnicos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='models',
            name='porcentagem_preenchimento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='qual_impressora',
            field=models.CharField(blank=True, choices=[('Ender_V2', 'Ender V2'), ('Ender_3-SE', 'Ender 3 SE'), ('Ender_3-S1', 'Ender 3 S1'), ('Ender_5-plus', 'Ender 5 Plus')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='resolucao',
            field=models.CharField(blank=True, choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='models',
            name='tipo_filamento',
            field=models.CharField(blank=True, choices=[('PLA', 'PLA'), ('ABS', 'ABS'), ('PETG', 'PETG')], max_length=20, null=True),
        ),
    ]
