# Generated by Django 5.2.4 on 2025-07-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='curso',
            field=models.CharField(choices=[('CC', 'Ciência da Computação'), ('ENG-QUI', 'Engenharia Química'), ('ENG-MEC', 'Engenharia Mecânica'), ('GEST-AGRO', 'Gestão do Agronegocio'), ('TECS', 'Cursos Técnicos')], default='CC', max_length=20),
        ),
    ]
