# Generated by Django 5.2.4 on 2025-08-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_models_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='Tipo_filamento',
            field=models.CharField(blank=True, choices=[('PLA', 'pla'), ('ABS', 'abs'), ('PETG', 'petg')], default='PLA', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='models',
            name='porcentagem_preenchimento',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='models',
            name='qual_impressora',
            field=models.CharField(blank=True, choices=[('Ender_V2', 'Ender V2'), ('Ender_3-SE', 'Ender 3 SE'), ('Ender_3-S1', 'Ender 3 S1'), ('Ender_5-plus', 'Ender 5 Plus')], default='Ender_V2', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='models',
            name='resolução',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='models',
            name='tipo_preenchimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='telefone',
            field=models.IntegerField(unique=True),
        ),
    ]
