# Generated by Django 5.2.4 on 2025-10-27 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_models_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='data_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
