# Generated by Django 5.2.4 on 2025-10-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_models_data_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
