# Generated by Django 5.2.4 on 2025-10-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_models_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='telefone',
            field=models.CharField(),
        ),
    ]
