# Generated by Django 5.2.4 on 2025-10-31 12:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_models_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='arq_upload',
            field=models.FileField(blank=True, null=True, upload_to=core.models.rename_uploaded_file),
        ),
        migrations.AlterField(
            model_name='models',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
