# Generated by Django 5.2.4 on 2025-11-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_models_arq_upload_alter_models_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PRODUCAO', 'Em produção'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20),
        ),
    ]
