# Generated by Django 5.2.4 on 2025-11-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_models_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PRODUCAO', 'Em produção'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', editable=False, max_length=20),
        ),
    ]
