# Generated by Django 5.2.4 on 2025-11-04 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historicostatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicostatus',
            name='impressao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_status', to='core.models'),
        ),
    ]
