# Generated by Django 5.2.4 on 2026-08-22 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_historicostatus_impressao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='porcentagem_preenchimento',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='models',
            name='quant_de_pecas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='models',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido com DDD. Ex.: (49) 99999-9999', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
