# Generated by Django 5.2.4 on 2026-08-23 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_models_porcentagem_preenchimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='data_envio',
        ),
    ]
