"""
Django settings for Impressora3D project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from django.contrib.messages import constants as message_constants
from django.core.exceptions import ImproperlyConfigured
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# cast=bool é obrigatório: sem ele, DEBUG=False no .env viraria a string
# "False", que o Python considera verdadeira.
DEBUG = config('DEBUG', default=False, cast=bool)

# SECURITY WARNING: keep the secret key used in production secret!
# Em desenvolvimento usamos uma chave descartável para o projeto subir sem
# configuração. Com DEBUG=False a chave passa a ser obrigatória.
SECRET_KEY = config('SECRET_KEY', default='')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-chave-de-desenvolvimento-nao-use-em-producao'
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY não definida. Copie o .env.example para .env e gere uma chave com:\n'
            '  python -c "from django.core.management.utils import get_random_secret_key; '
            'print(get_random_secret_key())"'
        )

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# O Render publica o domínio do serviço nesta variável. Sem acrescentá-la, todo
# request no domínio .onrender.com viraria HTTP 400.
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# O Django 4+ exige origem declarada para POST vindo de HTTPS. Sem isto, todo
# formulário no ar quebraria com "CSRF verification failed".
CSRF_TRUSTED_ORIGINS = [
    f'https://{host}' for host in ALLOWED_HOSTS if host not in ('localhost', '127.0.0.1')
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'core',
    'autenticacao',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serve os estáticos direto do processo Django. No Render não há
    # nginx na frente: sem ele, com DEBUG=False o site sobe sem nenhum CSS.
    # Precisa vir logo depois do SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Impressora3D.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Impressora3D.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Ordem de precedência:
#   1. DATABASE_URL  — o Render (e a maioria dos PaaS) entrega assim
#   2. DB_ENGINE + DB_*  — Postgres configurado peça por peça
#   3. SQLite        — padrão, para o projeto rodar logo após o clone
DATABASE_URL = config('DATABASE_URL', default='')
DB_ENGINE = config('DB_ENGINE', default='sqlite3')

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            # Reaproveita a conexão entre requests em vez de abrir uma nova a
            # cada um. O health check é o que torna isso seguro com bancos que
            # hibernam (o Neon suspende depois de alguns minutos ociosos):
            # a conexão morta é descartada em vez de estourar no meio da view.
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=not DEBUG,
        )
    }

    # O endpoint com "-pooler" no host (o recomendado pelo Neon) passa por
    # PgBouncer em modo transaction, que não suporta cursor no servidor.
    # Sem desligar, QuerySet.iterator() falharia em produção.
    if '-pooler' in DATABASES['default'].get('HOST', ''):
        DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
elif DB_ENGINE == 'sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': f'django.db.backends.{DB_ENGINE}',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }

MEDIA_URL = '/media/'
# Configurável para apontar a um disco persistente. ATENÇÃO: no plano gratuito
# do Render o disco é efêmero — os arquivos enviados pelos alunos somem a cada
# deploy ou reinício. Ver "Arquivos enviados" no README.
MEDIA_ROOT = config('MEDIA_ROOT', default=os.path.join(BASE_DIR, 'media'))

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Diretório onde os arquivos serão coletados ao rodar collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Não há STATICFILES_DIRS: cada app serve seus próprios estáticos a partir da
# sua pasta static/ (core/static/core/, etc.), via APP_DIRS do staticfiles.

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Em produção o WhiteNoise comprime os arquivos e põe um hash no nome,
        # o que permite cache eterno no navegador sem risco de servir versão
        # velha. Em desenvolvimento fica o backend simples, senão seria preciso
        # rodar collectstatic a cada alteração de CSS.
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# O Django marca erros com a tag 'error', mas o Bootstrap usa 'danger'.
# Traduzir aqui deixa o template escrever só alert-{{ message.tags }}.
MESSAGE_TAGS = {message_constants.ERROR: 'danger'}

LOGIN_URL = '/accounts/login/'          # usado por @login_required
LOGIN_REDIRECT_URL = '/'                # após login, voltamos pra home (opção 3)
LOGOUT_REDIRECT_URL = '/'               # após logout, volta pra home


# Segurança
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Tamanho máximo de um POST que não é arquivo (o limite de upload de arquivo
# fica em core/forms.TAMANHO_MAXIMO_MB).
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

# Endurecimentos que dependem de HTTPS; em desenvolvimento (http://localhost)
# ligá-los deixaria o site inacessível, então só valem com DEBUG=False.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Confia no cabeçalho do proxy reverso para saber que a origem era HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
